export const companyMocks = [
  {
    cnpj: "46.860.368/0001-20",
    fantasyName: "Letícia e Carlos Eduardo Entulhos ME",
    cep: "14806-121",
    suppliers: [
      {
        cnpj: "62.166.778/0001-22",
        fantasyName: "Caroline e Adriana Gráfica ME",
        cep: "59052-040",
        email: "representantes@carolineeadriana.com.br",
        id: 1,
        address: {
          cep: "59052-040",
          logradouro: "Rua Pastor Pires",
          complemento: "",
          bairro: "Quintas",
          localidade: "Natal",
          uf: "RN",
          ibge: "2408102",
          gia: "",
          ddd: "84",
          siafi: "1761",
        },
        isCNPJ: true,
      },
      {
        cnpj: "44.868.086/0001-44",
        fantasyName: "Emily e Fábio Borracharia",
        cep: "15502-227",
        email: "estoque@emilyefabio.com.br",
        id: 4,
        address: {
          cep: "15502-227",
          logradouro: "Rua José Vicente Mayor",
          complemento: "",
          bairro: "Jardim Orlando Mastrocola",
          localidade: "Votuporanga",
          uf: "SP",
          ibge: "3557105",
          gia: "7183",
          ddd: "17",
          siafi: "7245",
        },
        isCNPJ: true,
      },
      {
        cpf: "803.680.521-92",
        name: "Osvaldo Benício Isaac da Costa",
        cep: "06716-195",
        email: "osvaldo.benicio.dacosta@care-br.com",
        rg: "40.199.135-0",
        birthDate: "12/01/1952",
        id: 2,
        address: {
          cep: "06716-195",
          logradouro: "Rua Ponta Porã",
          complemento: "",
          bairro: "Barro Branco",
          localidade: "Cotia",
          uf: "SP",
          ibge: "3513009",
          gia: "2781",
          ddd: "11",
          siafi: "6361",
        },
        isCNPJ: false,
      },
    ],
    id: 3,
    address: {
      cep: "14806-121",
      logradouro: "Rua Mondo Archimedes Luppi",
      complemento: "",
      bairro: "Jardim Aclimação",
      localidade: "Araraquara",
      uf: "SP",
      ibge: "3503208",
      gia: "1818",
      ddd: "16",
      siafi: "6163",
    },
  },
  {
    cnpj: "79.461.539/0001-06",
    fantasyName: "Isaac e Ayla Telecom ME",
    cep: "13255-352",
    suppliers: [
      {
        cpf: "017.152.442-06",
        name: "Rafael Matheus Vicente Silva",
        cep: "69915-848",
        email: "rafael-silveira93@arganet.com.br",
        rg: "40.034.823-8",
        birthDate: "04/05/2005",
        id: 4,
        address: {
          cep: "69915-848",
          logradouro: "Rua Rio Caeté",
          complemento: "",
          bairro: "Portal da Amazônia",
          localidade: "Rio Branco",
          uf: "AC",
          ibge: "1200401",
          gia: "",
          ddd: "68",
          siafi: "0139",
        },
        isCNPJ: false,
      },
      {
        cpf: "244.890.572-02",
        name: "Miguel Cauê Davi Rodrigues",
        cep: "69909-004",
        email: "miguel@email.com",
        rg: "27.760.356-0",
        birthDate: "14/04/2006",
        id: 2,
        address: {
          cep: "69909-004",
          logradouro: "Rua Raiz de Davi",
          complemento: "",
          bairro: "Rosa Linda",
          localidade: "Rio Branco",
          uf: "AC",
          ibge: "1200401",
          gia: "",
          ddd: "68",
          siafi: "0139",
        },
        isCNPJ: false,
      },
    ],
    id: 4,
    address: {
      cep: "13255-352",
      logradouro: "Travessa Santo Francisconi",
      complemento: "",
      bairro: "Jardim da Luz",
      localidade: "Itatiba",
      uf: "SP",
      ibge: "3523404",
      gia: "3827",
      ddd: "11",
      siafi: "6569",
    },
  },
  {
    cnpj: "80.945.834/0001-09",
    fantasyName: "Tiago e Teresinha Marketing ME",
    cep: "08473-575",
    suppliers: [
      {
        cnpj: "62.166.778/0001-22",
        fantasyName: "Caroline e Adriana Gráfica ME",
        cep: "59052-040",
        email: "representantes@carolineeadriana.com.br",
        id: 1,
        address: {
          cep: "59052-040",
          logradouro: "Rua Pastor Pires",
          complemento: "",
          bairro: "Quintas",
          localidade: "Natal",
          uf: "RN",
          ibge: "2408102",
          gia: "",
          ddd: "84",
          siafi: "1761",
        },
        isCNPJ: true,
      },
      {
        cnpj: "44.868.086/0001-44",
        fantasyName: "Emily e Fábio Borracharia",
        cep: "15502-227",
        email: "estoque@emilyefabio.com.br",
        id: 4,
        address: {
          cep: "15502-227",
          logradouro: "Rua José Vicente Mayor",
          complemento: "",
          bairro: "Jardim Orlando Mastrocola",
          localidade: "Votuporanga",
          uf: "SP",
          ibge: "3557105",
          gia: "7183",
          ddd: "17",
          siafi: "7245",
        },
        isCNPJ: true,
      },
    ],
    id: 5,
    address: {
      cep: "08473-575",
      logradouro: "Travessa Antônio Carlos Piccino",
      complemento: "",
      bairro: "Conjunto Habitacional Barro Branco II",
      localidade: "São Paulo",
      uf: "SP",
      ibge: "3550308",
      gia: "1004",
      ddd: "11",
      siafi: "7107",
    },
  },
  {
    cnpj: "05.021.794/0001-93",
    fantasyName: "Heloise e Nelson Telecomunicações ME",
    cep: "83322-230",
    suppliers: [
      {
        cnpj: "89.044.154/0001-99",
        fantasyName: "Elisa e Raul Doces & Salgados",
        cep: "13409-008",
        email: "atendimento@elisaerauldocessalgadosltda.com.br",
        id: 3,
        address: {
          cep: "13409-008",
          logradouro: "Rua Praia Grande",
          complemento: "(Res Prq Piracicaba - Balbo)",
          bairro: "Santa Terezinha",
          localidade: "Piracicaba",
          uf: "SP",
          ibge: "3538709",
          gia: "5356",
          ddd: "19",
          siafi: "6875",
        },
        isCNPJ: true,
      },
    ],
    id: 6,
    address: {
      cep: "83322-230",
      logradouro: "Rua Rio Tietê",
      complemento: "",
      bairro: "Weissópolis",
      localidade: "Pinhais",
      uf: "PR",
      ibge: "4119152",
      gia: "",
      ddd: "41",
      siafi: "5453",
    },
  },
  {
    cnpj: "45.250.563/0001-76",
    fantasyName: "Antonella e Nair Filmagens ME",
    cep: "82720-365",
    suppliers: [
      {
        cpf: "721.551.809-42",
        name: "Antonio Yuri Tomás Duarte",
        cep: "86087-310",
        email: "antonio_yuri_duarte@mfb.com.br",
        rg: "41.429.686-2",
        birthDate: "03/05/2005",
        id: 1,
        address: {
          cep: "86087-310",
          logradouro: "Rua Inês Sanches Mendes",
          complemento: "",
          bairro: "Conjunto Farid Libos",
          localidade: "Londrina",
          uf: "PR",
          ibge: "4113700",
          gia: "",
          ddd: "43",
          siafi: "7667",
        },
        isCNPJ: false,
      },
    ],
    id: 7,
    address: {
      cep: "82720-365",
      logradouro: "Rua Helena Walesko Manika",
      complemento: "",
      bairro: "Santa Cândida",
      localidade: "Curitiba",
      uf: "PR",
      ibge: "4106902",
      gia: "",
      ddd: "41",
      siafi: "7535",
    },
  },
  {
    cnpj: "37.931.655/0001-93",
    fantasyName: "Melissa e Cauê Doces & Salgados",
    cep: "58407-368",
    suppliers: [
      {
        cpf: "721.551.809-42",
        name: "Antonio Yuri Tomás Duarte",
        cep: "86087-310",
        email: "antonio_yuri_duarte@mfb.com.br",
        rg: "41.429.686-2",
        birthDate: "03/05/2005",
        id: 1,
        address: {
          cep: "86087-310",
          logradouro: "Rua Inês Sanches Mendes",
          complemento: "",
          bairro: "Conjunto Farid Libos",
          localidade: "Londrina",
          uf: "PR",
          ibge: "4113700",
          gia: "",
          ddd: "43",
          siafi: "7667",
        },
        isCNPJ: false,
      },
      {
        cnpj: "89.044.154/0001-99",
        fantasyName: "Elisa e Raul Doces & Salgados",
        cep: "13409-008",
        email: "atendimento@gmail.com",
        id: 3,
        address: {
          cep: "13409-008",
          logradouro: "Rua Praia Grande",
          complemento: "(Res Prq Piracicaba - Balbo)",
          bairro: "Santa Terezinha",
          localidade: "Piracicaba",
          uf: "SP",
          ibge: "3538709",
          gia: "5356",
          ddd: "19",
          siafi: "6875",
        },
        isCNPJ: true,
      },
      {
        cpf: "244.890.572-02",
        name: "Miguel Cauê Davi Rodrigues",
        cep: "69909-004",
        email: "miguel@email.com",
        rg: "27.760.356-0",
        birthDate: "14/04/2006",
        id: 2,
        address: {
          cep: "69909-004",
          logradouro: "Rua Raiz de Davi",
          complemento: "",
          bairro: "Rosa Linda",
          localidade: "Rio Branco",
          uf: "AC",
          ibge: "1200401",
          gia: "",
          ddd: "68",
          siafi: "0139",
        },
        isCNPJ: false,
      },
    ],
    id: 7,
    address: {
      cep: "58407-368",
      logradouro: "Rua Paulo de Frontin",
      complemento: "",
      bairro: "José Pinheiro",
      localidade: "Campina Grande",
      uf: "PB",
      ibge: "2504009",
      gia: "",
      ddd: "83",
      siafi: "1981",
    },
  },
  {
    cnpj: "51.214.130/0001-68",
    fantasyName: "André e Alícia Corretores",
    cep: "58074-125",
    suppliers: [
      {
        cpf: "244.890.572-02",
        name: "Miguel Cauê Davi Rodrigues",
        cep: "69909-004",
        email: "miguel@email.com",
        rg: "27.760.356-0",
        birthDate: "14/04/2006",
        id: 2,
        address: {
          cep: "69909-004",
          logradouro: "Rua Raiz de Davi",
          complemento: "",
          bairro: "Rosa Linda",
          localidade: "Rio Branco",
          uf: "AC",
          ibge: "1200401",
          gia: "",
          ddd: "68",
          siafi: "0139",
        },
        isCNPJ: false,
      },
      {
        cpf: "017.152.442-06",
        name: "Rafael Matheus Vicente Silva",
        cep: "69915-848",
        email: "rafael-silveira93@arganet.com.br",
        rg: "40.034.823-8",
        birthDate: "04/05/2005",
        id: 4,
        address: {
          cep: "69915-848",
          logradouro: "Rua Rio Caeté",
          complemento: "",
          bairro: "Portal da Amazônia",
          localidade: "Rio Branco",
          uf: "AC",
          ibge: "1200401",
          gia: "",
          ddd: "68",
          siafi: "0139",
        },
        isCNPJ: false,
      },
    ],
    id: 8,
    address: {
      cep: "58074-125",
      logradouro: "Rua Severina Martins de Oliveira",
      complemento: "",
      bairro: "José Américo de Almeida",
      localidade: "João Pessoa",
      uf: "PB",
      ibge: "2507507",
      gia: "",
      ddd: "83",
      siafi: "2051",
    },
  },
  {
    cnpj: "33.324.386/0001-46",
    fantasyName: "Sabrina e Geraldo Filmagens",
    cep: "69920-036",
    suppliers: [],
    id: 9,
    address: {
      cep: "69920-036",
      logradouro: "Rua da Pitanga",
      complemento: "",
      bairro: "Mocinha Magalhães",
      localidade: "Rio Branco",
      uf: "AC",
      ibge: "1200401",
      gia: "",
      ddd: "68",
      siafi: "0139",
    },
  },
  {
    cnpj: "50.755.766/0001-54",
    fantasyName: "Lorena e Fernando Restaurante Ltda",
    cep: "58070-603",
    suppliers: [
      {
        cpf: "244.890.572-02",
        name: "Miguel Cauê Davi Rodrigues",
        cep: "69909-004",
        email: "miguel@email.com",
        rg: "27.760.356-0",
        birthDate: "14/04/2006",
        id: 2,
        address: {
          cep: "69909-004",
          logradouro: "Rua Raiz de Davi",
          complemento: "",
          bairro: "Rosa Linda",
          localidade: "Rio Branco",
          uf: "AC",
          ibge: "1200401",
          gia: "",
          ddd: "68",
          siafi: "0139",
        },
        isCNPJ: false,
      },
      {
        cnpj: "89.044.154/0001-99",
        fantasyName: "Elisa e Raul Doces & Salgados",
        cep: "13409-008",
        email: "atendimento@gmail.com",
        id: 3,
        address: {
          cep: "13409-008",
          logradouro: "Rua Praia Grande",
          complemento: "(Res Prq Piracicaba - Balbo)",
          bairro: "Santa Terezinha",
          localidade: "Piracicaba",
          uf: "SP",
          ibge: "3538709",
          gia: "5356",
          ddd: "19",
          siafi: "6875",
        },
        isCNPJ: true,
      },
      {
        cpf: "947.084.082-85",
        name: "Sérgio Caio da Luz",
        cep: "69920-036",
        email: "sergiocaiodaluz@zizafernandes.com",
        rg: "38.090.450-0",
        birthDate: "13/02/1950",
        id: 6,
        address: {
          cep: "69920-036",
          logradouro: "Rua da Pitanga",
          complemento: "",
          bairro: "Mocinha Magalhães",
          localidade: "Rio Branco",
          uf: "AC",
          ibge: "1200401",
          gia: "",
          ddd: "68",
          siafi: "0139",
        },
        isCNPJ: false,
      },
    ],
    id: 9,
    address: {
      cep: "58070-603",
      logradouro: "Rua Inglaterra",
      complemento: "",
      bairro: "Cristo Redentor",
      localidade: "João Pessoa",
      uf: "PB",
      ibge: "2507507",
      gia: "",
      ddd: "83",
      siafi: "2051",
    },
  },
];
